### ISSUE TITLE
Update gogs to gitea

### ISSUE THREAD

**Issue by hatmarch** [redhat-scholars/tekton-tutorial#32]
The current tutorial uses gogs which is fine, but [gitea](https://gitea.io/en-us/) is a more full featured self-hosted git that includes api support for the creation of pull-requests

I expect having gitea as part of the tutorial will add additional possibilities for integration points with argocd (e.g. tekton being able to create a pull request in the locally hosted gitea repo)

**Comment by kameshsampath** [comment]
fixed via #34
