### ISSUE TITLE
Build Cloud Native Application section is tasks is throwing error while building image

### ISSUE THREAD

**Issue by c-arnab** [redhat-scholars/tekton-tutorial#33]
PS C:\Users\ASUS> tkn taskrun describe build-app-run-j6s64
Name:              build-app-run-j6s64
Namespace:         tektontutorial
Task Ref:          build-app
Service Account:   pipeline
Timeout:           1h0m0s
Labels:
 app.kubernetes.io/managed-by=tekton-pipelines
 tekton.dev/task=build-app

Status

STARTED          DURATION    STATUS
16 minutes ago   1 minute    Failed

Message

"step-build-image" exited with code 125 (image: "quay.io/buildah/stable@sha256:50457efa4bbdf27f2f72f6a056d09008f1c26de673050bd436d3c5dc25249358"); for logs run: kubectl -n tektontutorial logs build-app-run-j6s64-pod-zfksz -c step-build-image

Input Resources

 NAME     RESOURCE REF
 source   git-source

Output Resources

 NAME         RESOURCE REF
 builtImage   tekton-tutorial-greeter-image

Params

 NAME         VALUE
 contextDir   springboot

Results

 No results

Workspaces

 No workspaces

Steps

 NAME                          STATUS
 git-source-source-2kr47       Completed
 create-dir-builtimage-hlkpd   Completed
 build-sources                 Completed
 build-image                   Error
 push-image                    Error
 image-digest-exporter-7pxj2   Error

Sidecars

No sidecars
PS C:\Users\ASUS> kubectl -n tektontutorial logs build-app-run-j6s64-pod-zfksz -c step-build-image
STEP 1: FROM registry.access.redhat.com/ubi8/openjdk-11
Getting image source signatures
Copying blob sha256:aebb8c5568533b57ee3da86262f7bff81383a2a624b9f54b9da3418705009901
Copying blob sha256:e5dfe0b7d65138db2a3e3ae0e2177d373860075e5ad8d3bfd662e985ec6da485
Copying blob sha256:0fd3b5213a9b4639d32bf2ef6a3d7cc9891c4d8b23639ff7ae99d66ecb490a70
Copying config sha256:87caa67388aec79d124240eb0455d71622e58c877424763136b163f86abea53a
Writing manifest to image destination
Storing signatures
STEP 2: COPY target/*.jar /deployments/
error building at STEP "COPY target/*.jar /deployments/": error adding sources [/workspace/source/springboot/target/*.jar]: error mounting build container "b4b23ccce8e8df1643afc548ce379d9e1fa72304ba11923dcec94d45690c18c3": failed to canonicalise path for "/var/lib/containers/storage/overlay/c67c1f70f28269111490f5497d93cb31c63c4296adf06681e1a142f5dce51d2c/merged": lstat /var/lib/containers/storage/overlay/c67c1f70f28269111490f5497d93cb31c63c4296adf06681e1a142f5dce51d2c/merged: invalid argument
[Tekton logs.txt](https://github.com/redhat-scholars/tekton-tutorial/files/5522551/Tekton.logs.txt)

**Comment by kameshsampath** [comment]
@c-arnab  - with latest buildah we have to specify `--storage-driver` to make the build successful  like https://github.com/redhat-scholars/tekton-tutorial/blob/release/v0.14.x/tasks/build-app-task.yaml#L52 and https://github.com/redhat-scholars/tekton-tutorial/blob/release/v0.14.x/tasks/build-app-task.yaml#L72.

I have fixed this staging branch and will have the same pushed to new release in upcoming release. until then you can update your build-app task as shown above to keep going

**Comment by kameshsampath** [comment]
@c-arnab  the change has been merged, you will see the update in next release, if you still face please do re-open the issue
