### ISSUE TITLE
image-digest-exporter fails after taskrun

### ISSUE THREAD

**Issue by x8-ball** [redhat-scholars/tekton-tutorial#57]
/question 

**Describe the Question**
I followed your tekton-tutorial until this point [TaskRun](https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/tasks.html#tekton-task-run). After executing the tkn task start build-app i encountered this strange error  and wondering why this happens? I can go along the tutorial without problems it just makes we wonder what happens here and what are the consequences of this error?
`[image-digest-exporter-7vhrm] {"level":"info","ts":1625051986.304341,"logger":"fallback-logger","caller":"imagedigestexporter/main.go:59","msg":"No index.json found for: builtImage","commit":"2ba62c8"}`

**To Reproduce**
1. Go to  [TaskRun](https://redhat-scholars.github.io/tekton-tutorial/tekton-tutorial/tasks.html#tekton-task-run)
2. Execute 
`tkn task start -n tektontutorial build-app \
  --inputresource='source=git-source' \
  --outputresource='builtImage=tekton-tutorial-greeter-image' \
  --showlog`
(I removed the --param contextDir='springboot'  because I'm having some issues that params of Tasks don't show up nor are accessible by cli but only with taskruns, but that's another story. I defaulted params to springboot in the buil-app-task.yaml file)
3. Scroll down to end of logs

**Expected behavior**
Expected no errors. Actually don't even expected this pod to be started

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS: WSL 2(Ubuntu 20.04) 
 - Tekton Version :  
 Client version: 2020-04-01T10:57:38Z
 Pipeline version: unknown
 - Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
 - Minikube Version: v1.21.0
commit: 76d74191d82c47883dc7e1319ef7cebd3e00ee11

**Additional context**
Add any other context about the question here.

**Comment by lordofthejars** [comment]
It is not a failure it is an info about an automatic task executed by Tekton. It can be ignored.
